name: Super-linter

on: push

jobs:
  super-lint:
    name:  Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

